name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@preview
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
              
      - name: Test
        env: 
          GOPROXY: "https://proxy.golang.org"
          CODECOV_TOKEN: ${{ secrets.SuperSecret }}
        run: | 
          go test -race -coverprofile=coverage.out -covermode=atomic ./...
          curl -s https://codecov.io/bash | bash
